source 'https://github.com/CocoaPods/Specs.git'


target 'XLEasyKitUtils_Example', :exclusive => true do
  pod 'XLEasyKitUtils', :path => '../'
end

target 'XLEasyKitUtils_Tests', :exclusive => true do
  pod 'XLEasyKitUtils', :path => '../'

  
end
